<?php

namespace AppBundle\Repository;

/**
 * TreasureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreasureTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
